# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  #boot.kernelPackages = pkgs.linuxPackages_latest;
  #boot.kernelPatches = [{ name = "Latest ath drivers"; patch = ./ath.patch; }];
  boot.kernelPackages = let
    custom_linux_pkg = { fetchurl, buildLinux, ... } @ args:

    buildLinux (args // rec {
      version = "5.11.0-rc5-wt-ath";
      modDirVersion = version;

      src = fetchurl {
        url = "https://git.kernel.org/pub/scm/linux/kernel/git/kvalo/ath.git/snapshot/ath-202101280720.tar.gz";
        sha256 = "b4bf8915602c6ab36e713016f1520d2602a9d82c1045c5e39df080d7fb65e734";
      };
      kernelPatches = [];

      extraMeta.branch = "5.11";
    } // (args.argsOverride or {}));
    custom_linux = pkgs.callPackage custom_linux_pkg{};
  in
  pkgs.recurseIntoAttrs (pkgs.linuxPackagesFor custom_linux);

  fileSystems."/" =
    { device = "pool/local/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "pool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CFFD-96A0";
      fsType = "vfat";
    };

  fileSystems."/cache" =
    { device = "pool/local/cache";
      fsType = "zfs";
    };

  fileSystems."/data" =
    { device = "pool/safe/data";
      fsType = "zfs";
    };

  swapDevices = [ ];
  hardware = {
    cpu.intel.updateMicrocode = true;
    enableRedistributableFirmware = true;
  };
  services.fstrim.enable = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
