# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.devShmSize = "75%";

  #boot.zfs.enableUnstable = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" "snd-seq" "snd-rawmidi" "snd-usb-audio" "btqca" "hci_qca" "hci_uart"];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
     options snd-intel-dspcfg dsp_driver=1
  '';

  # WARNING: don't bump kernel version without checking zfs support!
  boot.kernelPackages = pkgs.linuxPackages;

  boot.blacklistedKernelModules = [ "psmouse" ];
  services.fwupd.enable = true;

  fileSystems."/" =
    { device = "pool/local/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "pool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CFFD-96A0";
      fsType = "vfat";
    };

  fileSystems."/cache" =
    { device = "pool/local/cache";
      fsType = "zfs";
    };

  fileSystems."/data" =
    { device = "pool/safe/data";
      fsType = "zfs";
    };

  #swapDevices = [{
  #  device = "pool/swap";
  #}];

  hardware = {
    steam-hardware.enable = true;
    bluetooth.enable = true;
    bluetooth.powerOnBoot = true;
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        vaapiIntel
        intel-media-driver
        libva
        libvdpau-va-gl
        vaapiVdpau
        intel-compute-runtime
        ocl-icd
      ];
      extraPackages32 = with pkgs.pkgsi686Linux; [ libva ];
    };
    cpu.intel.updateMicrocode = true;
    enableRedistributableFirmware = true;
  };
  nixpkgs.config.packageOverrides = pkgs: {
    vaapiIntel = pkgs.vaapiIntel.override {
      enableHybridCodec = true;
    };
  };
  services.fstrim.enable = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
